server:
  port: 8081

spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:/Users/wool/Develop/WOOL/modu-link/data;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: admin
    password: qwerqwer123
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibername:
        format_sql: true
    hibernate:
      ddl-auto: update
      show_sql: true


myspring:
  test:
    name: wool
    age: 20

myspringListTest: banana,orange,apple